### ISSUE TITLE
Getting deployment log with im-client

### ISSUE THREAD

**Issue by sebastian-luna-valero** [grycap/im-client#112]
Hi,

Is it possible to retrieve the deployment log with `im-client`?

Thanks!

**Comment by micafer** [comment]
yes with with the `getcontmsg <infId>` option.

**Comment by sebastian-luna-valero** [comment]
Thank you!

**Comment by sebastian-luna-valero** [comment]
I just wanted to add that when `getstate <infId>` returns `configured`, then `getcontmsg <infId>` returns:
```
Msg Contextualizator: 

Contextualization disabled by the RADL/TOSCA template.
```
I was expecting to get the deployment log in that case as well.

**Comment by micafer** [comment]
This is the log.
It seems that you sent a deployment where the contextualization is disabled, so no log are displayed.

**Comment by sebastian-luna-valero** [comment]
This is what I sent
```yaml
tosca_definitions_version: tosca_simple_yaml_1_0

imports:
- grycap_custom_types: https://raw.githubusercontent.com/grycap/tosca/main/custom_types.yaml

topology_template:
  node_templates:
    simple_node:
      type: tosca.nodes.indigo.Compute
      capabilities:
        endpoint:
          properties:
            network_name: PUBLIC
        host:
          properties:
            num_cpus: 2
            mem_size: 4 GB
        os:
          properties:
            image: appdb://IN2P3-IRES/egi.ubuntu.24.04?vo.access.egi.eu
  outputs:
    node_ip:
      value: { get_attribute: [ simple_node, public_address, 0 ] }
    node_creds:
      value: { get_attribute: [ simple_node, endpoint, credential, 0 ] }
```
I submitted it with:
```bash
im_client.py create_wait_outputs -a auth.dat tosca.yaml
```
How do I request the logs?

**Comment by micafer** [comment]
This template only has one compute node without anything to install so the contextualization is disabled
If  you want to force the ansible installation you can do something like we use in the simple node in the dashboard:

```yaml
      # Add dummy task to activate context
      interfaces:
        Standard:
          configure:
            implementation: https://raw.githubusercontent.com/grycap/tosca/main/artifacts/dummy.yml
```
https://github.com/grycap/tosca/blob/21dbcd18b213f5843a8f980b7af05ee55e5c87c7/templates/simple-node-disk.yml#L153-L157
