### ISSUE TITLE
Order of ids in auth.dat causing issues

### ISSUE THREAD

**Issue by sebastian-luna-valero** [grycap/im-client#86]
Hi,

If I use this `auth.dat`
```
id = im; type = InfrastructureManager; token = command(oidc-token OIDC_ACCOUNT)
id = egi1; type = EGI; host = CESNET-MCC; vo = training.egi.eu; token = command(oidc-token OIDC_ACCOUNT)
id = egi2; type = EGI; host = GSI-LCG2; vo = training.egi.eu; token = command(oidc-token OIDC_ACCOUNT)
id = egi3; type = EGI; host = IFCA-LCG2; vo = training.egi.eu; token = command(oidc-token OIDC_ACCOUNT)
id = egi4; type = EGI; host = IISAS-FedCloud; vo = training.egi.eu; token = command(oidc-token OIDC_ACCOUNT)
id = egi5; type = EGI; host = NCG-INGRID-PT; vo = training.egi.eu; token = command(oidc-token OIDC_ACCOUNT)
id = egi6; type = EGI; host = CESGA; vo = vo.access.egi.eu; token = command(oidc-token OIDC_ACCOUNT)
id = egi7; type = EGI; host = CYFRONET-CLOUD; vo = vo.access.egi.eu; token = command(oidc-token OIDC_ACCOUNT)
id = egi8; type = EGI; host = GSI-LCG2; vo = vo.access.egi.eu; token = command(oidc-token OIDC_ACCOUNT)
id = egi9; type = EGI; host = IFCA-LCG2; vo = vo.access.egi.eu; token = command(oidc-token OIDC_ACCOUNT)
id = egi10; type = EGI; host = IISAS-FedCloud; vo = vo.access.egi.eu; token = command(oidc-token OIDC_ACCOUNT)
id = egi11; type = EGI; host = IN2P3-IRES; vo = vo.access.egi.eu; token = command(oidc-token OIDC_ACCOUNT)
id = egi12; type = EGI; host = INFN-PADOVA-STACK; vo = vo.access.egi.eu; token = command(oidc-token OIDC_ACCOUNT)
id = egi13; type = EGI; host = SCAI; vo = vo.access.egi.eu; token = command(oidc-token OIDC_ACCOUNT)
id = egi14; type = EGI; host = TR-FC1-ULAKBIM; vo = vo.access.egi.eu; token = command(oidc-token OIDC_ACCOUNT)
id = egi15; type = EGI; host = UNIV-LILLE; vo = vo.access.egi.eu; token = command(oidc-token OIDC_ACCOUNT)
```
and this `tosca.yml`:
```
tosca_definitions_version: tosca_simple_yaml_1_0
imports:
- indigo_custom_types: https://raw.githubusercontent.com/indigo-dc/tosca-types/master/custom_types.yaml
topology_template:
  node_templates:
    simple_node:
      type: tosca.nodes.indigo.Compute
      capabilities:
        endpoint:
          properties:
            network_name: PUBLIC
        host:
          properties:
            num_cpus: 2
            mem_size: 4 GB
        os:
          properties:
            image: appdb://IISAS-FedCloud/egi.ubuntu.20.04?vo.access.egi.eu
  outputs:
    node_ip:
      value: { get_attribute: [ simple_node, public_address, 0 ] }
    node_creds:
      value: { get_attribute: [ simple_node, endpoint, credential, 0 ] }
```
I get
```
$ im_client.py create tosca.yml

ERROR creating the infrastructure: Error Creating Inf.: Error adding VMs: Error launching the VMs of type simple_node to cloud ID egi4 of type EGI. Attempt 1: Error: 404 Not Found {'message': 'No image found with ID 0161b224-da2c-4919-b9ac-5027239e40ae<br /><br />\n\n\n', 'code': '404 Not Found', 'title': 'Not Found'}
```
However, if I comment following line in `auth.dat`:
```
# id = egi4; type = EGI; host = IISAS-FedCloud; vo = training.egi.eu; token = command(oidc-token OIDC_ACCOUNT)
```
It works.

Is this behavior expected?

Many thanks,
Sebastian
